sources/ajax/urls.py
from django.conf.urls import patterns, url

from dota.forms import FantasyForm


urlpatterns = patterns('ajax.views_forms',
    url(r'^forms/submit/(?P<label>[^/]+)/$',   'submit',   name='form-submit'),
)

urlpatterns += patterns('ajax.views_fantasy',
    url(r'^dota/players/buy/(?P<id>[0-9]+)/$',  'buy',  name='dota-fantasy-buy'),
    url(r'^dota/players/sell/(?P<id>[0-9]+)/$', 'sell', name='dota-fantasy-sell'),
)

urlpatterns += patterns('ajax.views_standard',
    url(r'^dota/standard/submit/$', 'submit', name='dota-standard-submit'),
)

sources/dota/urls.py
from django.conf.urls import patterns, url

from dota.views_leagues import LeaguesListView
from dota.views_ranking import RankingListView


# Homemade views
urlpatterns = patterns('dota',
    url(r'^fantasy/$',  'views_fantasy.index',  name='dota-fantasy'),
    url(r'^home/$',     'views_home.index',     name='dota-home'),
    url(r'^matches/$',  'views_matches.index',  name='dota-matches'),
    url(r'^standard/$', 'views_standard.index', name='dota-standard'),
)

# Generic views
urlpatterns += patterns('',
    url(r'^leagues/$', LeaguesListView.as_view(), name='dota-leagues'),
    url(r'^ranking/$', RankingListView.as_view(), name='dota-ranking'),
)

sources/esportbets/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from tastypie.api import Api

from accounts.api import UserResource
from dota.api import *


admin.autodiscover()

# Django URLs
urlpatterns = patterns('',
    url(r'^admin/',     include(admin.site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^i18n/',      include('django.conf.urls.i18n')),
)

# Homemade URLs
urlpatterns += patterns('',
    url(r'^accounts/', include('accounts.urls')),
    url(r'^ajax/',     include('ajax.urls')),
    url(r'^dota/',     include('dota.urls')),
    url(r'^home/',     include('home.urls')),
)

# Third party URLs
API = {
    'dota':      Api(api_name='1'),
    'standard':  Api(api_name='0'),
    'starcraft': Api(api_name='2'),
}
API['dota'].register(BetResource())
API['dota'].register(EncounterResource())
API['dota'].register(FantasyResource())
API['dota'].register(HeroResource())
API['dota'].register(LeagueResource())
API['dota'].register(MatchResource())
API['dota'].register(PlayerResource())
API['dota'].register(TeamResource())
API['standard'].register(UserResource())
urlpatterns += patterns('',
    url(r'^api/',      include(API['dota'].urls)),
    url(r'^api/',      include(API['standard'].urls)),
    url(r'^api/',      include(API['starcraft'].urls)),
    url(r'^accounts/', include('userena.urls')),
)

# Flatpage URLs
urlpatterns += patterns('django.contrib.flatpages.views',
    url(r'^about/$', 'flatpage', { 'url':'/about/' }, name='about'),
)

sources/home/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('home.views',
    url(r'^$', 'home', name='home'),
)

sources/accounts/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models

from helpers.baseclasses.basehuman import BaseHuman
from userena.models import UserenaBaseProfile


# ──────────────────────────────────────────────────────────────────────────────
class Profile(BaseHuman, UserenaBaseProfile):
    """Profile model to use to store the user datas
    """

    user    = models.OneToOneField(User, unique=True, related_name='profile')
    credits = models.FloatField(default=100000.0)
    # ──────────────────────────────────────
    def __unicode__(self):
        return unicode(self.user.username)

sources/dota/models.py
#! -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _

from helpers.baseclasses.basebet import BaseBet
from helpers.baseclasses.baseencounter import BaseEncounter
from helpers.baseclasses.basehuman import GENDERS
from helpers.baseclasses.baseplayer import BasePlayer
from helpers.baseclasses.baseteam import BaseTeam


POSITIONS = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
)

TEAMS = (
    ('D', 'Dire'),
    ('R', 'Radiant'),
)


# ──────────────────────────────────────────────────────────────────────────────
class Hero(models.Model):
    """Stores Dota 2 heroes
    """

    steam_id = models.PositiveIntegerField(unique=True)
    vanilla  = models.CharField(max_length=32, unique=True)
    name     = models.CharField(max_length=32, unique=True, blank=True, null=True)

    def __unicode__(self):
        return unicode(self.name.title())

    class Meta:
        verbose_name_plural = 'heroes'


# ──────────────────────────────────────────────────────────────────────────────
class League(models.Model):
    """Stores Dota 2 leagues
    """

    steam_id    = models.PositiveIntegerField(unique=True)
    name        = models.CharField(max_length=64, unique=True)
    description = models.TextField(max_length=512)
    url         = models.URLField(max_length=256)

    def __unicode__(self):
        return unicode(self.name)


# ──────────────────────────────────────────────────────────────────────────────
class Match(BaseEncounter):
    """Stores Dota 2 matches
    """

    steam_id = models.PositiveIntegerField(unique=True)
    dire     = models.CharField(max_length=32, default='Dire Team')
    radiant  = models.CharField(max_length=32, default='Radiant Team')
    result   = models.CharField(max_length=1, choices=TEAMS, blank=True, null=True)
    duration = models.PositiveSmallIntegerField(blank=True, null=True)

    def __unicode__(self):
        return unicode(self.steam_id)

    class Meta:
        verbose_name_plural = 'matches'


# ──────────────────────────────────────────────────────────────────────────────
class Team(BaseTeam):
    """Stores Dota 2 teams
    """

    name = models.CharField(max_length=32, unique=True)
    slug = models.CharField(max_length=4, unique=True)

    def __unicode__(self):
        return unicode(self.name)


# ──────────────────────────────────────────────────────────────────────────────
class Player(BasePlayer):
    """Stores Dota 2 players
    """

    team     = models.ForeignKey(Team, on_delete=models.SET_NULL, blank=True, null=True)
    position = models.CharField(max_length=1, choices=POSITIONS, default=POSITIONS[0][0])


# ──────────────────────────────────────────────────────────────────────────────
class Fantasy(BaseTeam):
    """Stores Dota 2 fantasy teams
    """

    user        = models.ForeignKey(User, unique=True)
    name        = models.CharField(max_length=32, default=_('My Fantasy Team'))
    slug        = models.CharField(max_length=4, default=_('MFT'))
    players     = models.ManyToManyField(Player, blank=True)
    players.help_text = ''  # The one true way of removing things you didn't add yourself

    def __unicode__(self):
        return unicode(self.user)

    class Meta:
        verbose_name_plural = 'fantasies'


# ──────────────────────────────────────────────────────────────────────────────
class Encounter(BaseEncounter):
    """Store Dota 2 encounters
    """

    dire    = models.ForeignKey(Team, related_name='dire')
    radiant = models.ForeignKey(Team, related_name='radiant')


# ──────────────────────────────────────────────────────────────────────────────
class Bet(BaseBet):
    """Stores Dota 2 standard bets
    """

    encounter = models.ForeignKey(Encounter, related_name='bets')
    bet       = models.CharField(max_length=1, choices=TEAMS)

    def __unicode__(self):
        return unicode('{}'.format(self.encounter))

sources/dota/forms.py
#! -*- coding: utf-8 -*-
from django import forms

from dota.models import Fantasy


# ──────────────────────────────────────────────────────────────────────────────
class FantasyForm(forms.ModelForm):
    """Form for the user to edit his Dota fantasy team, inherit from ``models.Fantasy``
    """

    class Meta:
        model = Fantasy
        exclude = ('user', 'players')

sources/home/views.py
#! -*- coding: utf-8 -*-
from django.shortcuts import render


# ──────────────────────────────────────────────────────────────────────────────
def home(request):
    '''The homepage
    :param request: the Django request object
    :returns: <type 'HttpResponse'>
    '''

    # Rendering the page
    context = {}
    response = render(request, 'home/home.html', context)
    return response

sources/esportbets/templates/dota/base.html
{% extends "base/base.html" %}
{% load i18n %}


{% block title %}Dota 2{{ block.super }}{% endblock title %}

sources/esportbets/templates/dota/fantasy.html
{% extends "dota/base.html" %}
{% load humanize %}
{% load i18n %}
{% load staticfiles %}


{% block script %}
{{ block.super }}
<script type="text/javascript" src="{% static 'js/homemade/dota.fantasy.js' %}"></script>
{% endblock script %}


{% block js-ready %}
{{ block.super }}
InitializeForms(['#form-fantasy']);
InitializePlayerPool();
UpdatePlayerCount();
{% endblock js-ready %}


{% block content %}
{% if form %}
<!-- Start user team -->
<h2>{% trans "name your fantasy team" %}</h2>
<form id="form-fantasy" action="" method="post">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
</form><br /><br />
<!-- End user team -->

{% if players %}
<!-- Start fantasy -->
<h2>{% trans "build your fantasy team" %}</h2>
<div>
    <p>
        {% trans "Credits" %}:
        <span id="credits-amount">{{ profile.credits|floatformat:2|intcomma }}</span>
    </p><br />

    <!-- Start user players -->
    <p>
        {% trans "Players" %} (<span id="players-count">0</span>/5):
        <a class="ninja-toggler">{% trans "toggle" %}</a>
    </p>
    <div id="players"><br />
        {% for p in players %}
        <div class="wrapper-pool">
            <div class="pool{% if forloop.last %} last{% endif %}">
                <div id="position-{{ forloop.counter }}" class="wrapper-player last{% if not p %} empty{% endif %}">
                    {% if p %}
                    <a class="player" onclick="SellPlayer({{ p.pk }}, {{ p.position }}, '{{ p }}', '{{ p.price }}');">
                        <span class="text">{{ p }}</span>
                        <span class="price">{{ p.price|floatformat:2|intcomma }}</span>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
        <div style="clear:both;"></div>
    </div><br />
    <!-- End user players -->

    <!-- Start player pool -->
    <p>
        {% trans "Player pool" %}:
        <a class="ninja-toggler">{% trans "toggle" %}</a>
    </p>
    <div id="pool" class="ninja"><br />
        {% for pool in pools %}
        <div class="wrapper-pool">
            <div class="pool-position">{% trans "Position" %} {{ forloop.counter }}</div>
            <div id="pool-{{ forloop.counter }}" class="pool{% if forloop.last %} last{% endif %}">
                {% for p in pool %}
                <div id="player-{{ p.pk }}" class="wrapper-player{% if forloop.last %} last{% endif %}{% if p in players %} empty{% endif %}">
                    {% if not p in players %}
                    <a class="player" onclick="BuyPlayer({{ p.pk }}, {{ p.position }}, '{{ p }}', '{{ p.price }}');">
                        <span class="text">{{ p }}</span>
                        <span class="price">{{ p.price|floatformat:2|intcomma }}</span>
                    </a>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <div style="clear:both;"></div>
    </div>
    <!-- End player pool -->
</div>
<!-- End fantasy -->
{% endif %}
{% endif %}
{% endblock content %}

sources/esportbets/templates/dota/home.html
{% extends "dota/base.html" %}


{% block content %}
<h2>home</h2>
{% endblock content %}

sources/esportbets/templates/dota/leagues.html
{% extends "dota/base.html" %}
{% load i18n %}

{% block content %}
<h2>{% trans "list of leagues" %}</h2>
<table class="table">
    <thead>
        <tr>
            <th>{% trans "Name" %}</th>
            <th>{% trans "URL" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for league in league_list %}
        <tr>
            <td>{{ league }}</td>
            <td>{% if league.url %}<a class="external" href="{{ league.url }}">{{ league.url }}</a>{% else %}{% trans "No provided address" %}{% endif %}</td>
        </tr>
        {% empty %}
        <tr><td class="empty" colspan="2">{% trans "No league available" %}</td></tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

sources/esportbets/templates/dota/matches.html
{% extends "dota/base.html" %}
{% load i18n %}


{% block content %}
<h2>{% trans "history of matches" %}</h2>
<table id="matches" class="table">
    <thead>
        <tr>
            <th>{% trans "Match ID" %}</th>
            <th>{% trans "League" %}</th>
            <th>{% trans "Date" %}</th>
            <th>Dire</th>
            <th>Radiant</th>
            <th>{% trans "Duration" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for match in matches %}
        <tr>
            <td>
                <a class="external" href="http://dotabuff.com/matches/{{ match.steam_id }}">
                    {{ match.steam_id }}
                </a>
            </td>
            <td>
                {% with l=match.league %}
                {% if l %}
                <a class="external" href="{{ l.url }}">{{ l }}</a>
                {% else %}
                {% trans "Unknown league" %}
                {% endif %}
                {% endwith %}
            </td>
            <td>{{ match.date|timesince }} {% trans "ago" %}</td>
            <td>
                <span class="team{% ifequal match.result 'D' %} victory{% else %} defeat{% endifequal %}">
                    {{ match.dire }}
                </span>
            </td>
            <td>
                <span class="team{% ifequal match.result 'R' %} victory{% else %} defeat{% endifequal %}">
                    {{ match.radiant }}
                </span>
            </td>
            <td>{{ match.duration }}</td>
        </tr>
        {% empty %}
        <tr><td class="empty" colspan="6">{% trans "No match available" %}</td></tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

sources/esportbets/templates/dota/ranking.html
{% extends "dota/base.html" %}
{% load humanize %}
{% load i18n %}


{% block content %}
<h2>{% trans "user ranking" %}</h2>
<table class="table">
    <thead>
        <tr>
            <th>{% trans "Username" %}</th>
            <th>{% trans "Credits" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for profile in profile_list %}
        <tr>
            <td><a href="{% url 'userena_profile_detail' profile.user.username %}">{{ profile }}</a></td>
            <td>{{ profile.credits|floatformat:2|intcomma }}</td>
        </tr>
        {% empty %}
        <tr><td class="empty" colspan="2">{% trans "No user available" %}</td></tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

sources/esportbets/templates/dota/standard.html
{% extends "dota/base.html" %}
{% load i18n %}
{% load range %}
{% load staticfiles %}


{% block script %}
{{ block.super }}
<script type="text/javascript" src="{% static 'js/homemade/dota.standard.js' %}"></script>
{% endblock script %}


{% block js-ready %}
{{ block.super }}
InitializeStandard();
{% endblock js-ready %}


{% block content %}
<!-- Start upcoming encounters -->
<h2>{% trans "upcoming encounters" %}</h2>
<table id="encounters" class="table">
    <thead>
        <tr>
            <th class="league">{% trans "League" %}</th>
            <th class="dire">Dire</th>
            <th class="radiant">Radiant</th>
            <th class="date">{% trans "Date" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for encounter in upcoming %}
        {% with e=encounter %}
        <tr id="encounter-{{ e.pk }}" class="encounter interactive" data-pk="{{ e.pk }}">
            <td>
                {% if e.league %}
                <a class="external" href="{{ e.league.url }}">{{ e.league }}</a>
                {% else %}
                {% trans "Unknown league" %}
                {% endif %}
            </td>
            <td class="faction dire" data-faction="dire">
                <p><span class="team">{{ e.dire }}</span> <a style="float:right" class="bet-toggler">{% trans "Bet" %}</a></p>
                <div class="details ninja">
                    <div class="odds"><div class="odds-winning" style="width:{{ e.odds_dire }}%;"></div></div>
                </div>
            </td>
            <td class="faction radiant" data-faction="radiant">
                <p><span class="team">{{ e.radiant }}</span> <a style="float:right" class="bet-toggler">{% trans "Bet" %}</a></p>
                <div class="details ninja">
                    <div class="odds"><div class="odds-winning" style="width:{{ e.odds_radiant }}%;"></div></div>
                </div>
            </td>
            <td>
                <p>{% trans "In" %} {{ e.date|timeuntil }}</p>
                <div class="details ninja"><p>{{ e.date }}</p></div>
            </td>
        </tr>
        {% endwith %}
        {% empty %}
        <tr><td class="center" colspan="4">{% trans "No upcoming encounter" %}</td></tr>
        {% endfor %}
        <tr><td colspan="4" style="padding:0px;"></td></tr>
    </tbody>
</table>
<div class="table-toolbar">
    <button id="refresh-bets" class="jquerized" type="button" disabled>
        <span class="ui-icon ui-icon-refresh">
    </button>
    <button id="submit-bets" class="jquerized" type="button" onclick="ConfirmBets();" disabled>
        <span class="ui-icon ui-icon-check">
    </button>
    <div style="clear:both;"></div>
</div><br /><br />
<!-- End upcoming encounters -->

<!-- Start pending bets -->
<h2>{% trans "pending bets" %}</h2>
<table id="bets" class="table">
    <thead>
        <tr>
            <th class="league">{% trans "League" %}</th>
            <th class="dire">Dire</th>
            <th class="radiant">Radiant</th>
            <th class="date">{% trans "Date" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for bet in pending %}
        {% with e=bet.encounter %}
        <tr class="interactive">
            <td>
                {% if e.league %}
                <a class="external" href="{{ e.league.url }}">{{ e.league }}</a>
                {% else %}
                {% trans "Unknown league" %}
                {% endif %}
            </td>
            <td>
                <p class="team {% ifequal bet.bet 'D' %}victory{% else %}defeat{% endifequal %}">{{ e.dire }}</p>
                <div class="details ninja"></div>
            </td>
            <td>
                <p class="team {% ifequal bet.bet 'R' %}victory{% else %}defeat{% endifequal %}">{{ e.radiant }}</p>
                <div class="details ninja"></div>
            </td>
            <td>
                <span>{% trans "In" %} {{ e.date|timeuntil }}</span>
                <div class="details ninja"><p>{{ e.date }}</p></div>
            </td>
        </tr>
        {% endwith %}
        {% empty %}
        <tr>
            <td style="text-align:center;" colspan="4">{% trans "No pending bet" %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<!-- End pending bets -->
{% endblock content %}